### ISSUE TITLE
defineEventStreamsToLoad throws exception when eventstream does not exist

### ISSUE THREAD

**Issue by edro** [adrai/node-cqrs-domain#107]
[defineEventStreamsToLoad](https://github.com/adrai/node-cqrs-domain/blob/82e2f0a2d963c799d3f2d0b0cddc2567918ac78c/lib/definitions/command.js#L253) throws exception "_No event stream found for evt with id:..._" when eventstream with requested **aggregateId** does not not exist in eventstore before. Expectation - creating new eventstream with this **aggregateId**

**Comment by adrai** [comment]
Are you making a bigger redesign in your domain and you need to handle a command on a new aggregate?
i.e. merging 2 event streams into a new aggragate?

**Comment by edro** [comment]
I'd like to convert an input command payload using of an external service to a new aggregateId. For example: domain command contains phone number (car plate, tag etc.) in in an arbitrary manner, but i need to build (or get) aggrgate using that number as aggregate identity.

**Comment by adrai** [comment]
Isn't `defineCommandAwareAggregateIdGenerator` suitable for your use case?

**Comment by adrai** [comment]
there's always the possibility to define an own command handler => https://github.com/adrai/node-cqrs-domain#command-handler-be-careful
