### ISSUE TITLE
Domain.stop()

### ISSUE THREAD

**Issue by alemhnan** [adrai/node-cqrs-domain#110]
Is it possible to stop the domain programmatically? 
It is useful for testing purposes. Now we need to stop with a process.exit. That makes more difficult to use a test runner.

**Comment by adrai** [comment]
if you call disconnect() on this objects:
```javascript
domain.eventStore.disconnect()
domain.aggregateLock.disconnect()
if (domain.commandBumper) domain.commandBumper.disconnect()
```
this should do the trick

**Comment by alemhnan** [comment]
Super. Thanks a lot.
