### ISSUE TITLE
definePreLoadCondition handing commands version

### ISSUE THREAD

**Issue by repkins** [adrai/node-cqrs-domain#111]
Hello, @adrai!

I have noticed a issue while handling a command in specific versions with pre-load conditions.

**Given** pre-load condition definition handles commands at version, for example, **0**.
**When** comes command to domain handler with version **1**,
**Then** instead of not handling such command in given pre-load condition, its does opposite, i.e., handles command at given pre-load condition, despite of command version is not equal to given pre-load condition version.

Please, take a look!

**Comment by adrai** [comment]
should be fixed with new version v2.9.6
