### ISSUE TITLE
Command revision verifying while disabled persistance

### ISSUE THREAD

**Issue by repkins** [adrai/node-cqrs-domain#112]
Hello, @adrai!

I have noticed a potential bug about how default command handler verifies command revision with associated aggregate. While aggregate has disabled persistence using definition property `disablePersistence: true`, I don't think it should verify revision of incoming command with such aggregate because there is no stored previous events to build aggregate from them so far.

**Comment by adrai** [comment]
So would you suggest to not verify the revision when disablePersistence is set to true, right?

**Comment by adrai** [comment]
v2.9.8

**Comment by repkins** [comment]
Yap, i would suggest. :-)
