### ISSUE TITLE
Documentation of features

### ISSUE THREAD

**Issue by xander-mbaka** [adrai/node-cqrs-domain#118]
Hi,

Was wondering where I might get some more info on how the following features work, their options and caveats:

1. AggregateLock - Domain
2. Deduplication - Domain
3. RevisionGuard - Saga

Any pointers?

**Comment by adrai** [comment]
1. AggregateLock - Domain
   - AggregateLock prevents concurrent update of your aggregate (if you don't have this already solved in the messaging layer)

2. Deduplication - Domain
   - Checks the command id and ignores commands that had the same command id in the past...

3. RevisionGuard - Saga + EvenDenormalizer
   - https://github.com/adrai/node-cqrs-eventdenormalizer/issues/50

**Comment by xander-mbaka** [comment]
Thanks,

Is there an inbuilt way to guard against command payload duplication? To guard from user sending the same cmd payload (e.g from UI double click instead of single click)?

Or I should resort to smth like:

var hash = require('object-hash');

var data = {a: 1, b: 2};

var cmd = new Backbone.CQRS.Command({
              id: hash(data),
              command: 'reverseTransaction',
              payload: data,
});
cmd.emit();

So that the command id is always unique to the payload

**Comment by adrai** [comment]
No there is nothing inbuilt like that...

**Comment by adrai** [comment]
I don't know if it's a good idea to have the commad id always unique to the payload...

**Comment by adrai** [comment]
think of an increment command looking always the same... will be rejected (because of deduplication) but in reality correct.

**Comment by adrai** [comment]
Try to block the ui action for a couple of seconds or block until the event arrived...

**Comment by xander-mbaka** [comment]
Much thanks
