### ISSUE TITLE
Is it possible to replace the t4-validation?

### ISSUE THREAD

**Issue by blissi** [adrai/node-cqrs-domain#133]
Hallo,

I'd like to use Joi for validating the commands. Is it possible to replace the built-in t4-validation with something different? What's the purpose of the validator extension? Can it be used for this?

Thanks, Steven

**Comment by nanov** [comment]
Hi!

It is totally possible to replace the default ( probably outdated ) validator with something else. We use in production [ajv](https://github.com/epoberezkin/ajv).

With that being said, the validator must validate an object against [JSON schemas](https://json-schema.org/), which in my opinion is a far better option than JOI taking into account its standardisation cross-language and cross-platfrom support.

Alternatively you could implement completely custom validations in pre-load-conditions ( the validation is basically the same ) and throw validation errors as wish there. 

If you decide to go with the JSON schema way, i would be more than happy to provide you with an example that uses custom validator.

**Comment by blissi** [comment]
@nanov  I'm not limited to Joi and would highly appreciate your ajv-example.

**Comment by nanov** [comment]
Ok,

I've tried to come up with [something](https://github.com/nanov/cqrs-examples-core) quickly.
I will continue to update those examples when I find the time as i truly believe those are useful.

As per your specific question :

Complete AJV validation and error reporting is implemented in this example. Take a look at it and how it works, and let me know if this is helpful.

**Comment by blissi** [comment]
Thanks, that's definately helpful! I'll play around with it.
