### ISSUE TITLE
Context and aggregateId

### ISSUE THREAD

**Issue by bikerp** [adrai/node-cqrs-domain#142]
Hi,
what is the exact purpose of the context?
Fo example can I have two aggregates with the same name (e.g. user) but in different contexts (hr and sales). Can these aggregates use the same aggregateId for the same person e.g. email address?

**Comment by nanov** [comment]
In short, yes, two aggregates with the same name on different contexts are completely separated, therefore they can ( and probably should ) use the same ID. 

As of what is the purpose of context, I suggest you dive into [DDD principles](https://thinkbeforecoding.com/post/2010/04/17/Event-Sourcing-and-CQRS-Bounded-Contexts) to find out.

**Comment by bikerp** [comment]
Thank you for your answer. I know the DDD and I just wanted to be sure if the context in cqrs-domain means the same.

**Comment by bikerp** [comment]
I have defined aggreate `user` in file `aggregate.js`
```
module.exports = require('cqrs-domain').defineAggregate({
    name: 'user',
    defaultCommandPayload: 'payload',
    defaultEventPayload: 'payload',
});
```
I have noticed that aggregate name is not mentioned in event store records. Is it itentional?

**Comment by nanov** [comment]
It definitely is on the ```aggregate``` property.

**Comment by bikerp** [comment]
You are right. I forgot to put `aggregate: 'aggregate.name',` into `defineEvent`
Thanks
