### ISSUE TITLE
How to clear/init

### ISSUE THREAD

**Issue by bikerp** [adrai/node-cqrs-domain#144]
Hi,
I'd like to test pre-conditions for various commands. Is there a possibility to clear the eventstore in tests? I tried to run `domain.init()` before each test but it seems that the events are not discarded.
Thanks
Pavel

**Comment by adrai** [comment]
create a new domain like here: https://github.com/adrai/node-cqrs-domain/blob/master/test/integration/integrationTest.js
or try to call `domain.eventstore.store.clear()`

**Comment by bikerp** [comment]
@adrai Yes, the `domain.eventStore.store.clear()` did the trick. Thanks
