### ISSUE TITLE
Same event name in different contexts

### ISSUE THREAD

**Issue by bikerp** [adrai/node-cqrs-domain#145]
Hi,

let's say I have two different contexts: Books and Services. Both contexts contains Order aggregate.
Is it a common practice that same event name exists in different contexts i.e. OrderAccepted? Or the event name should be unique i.e. BookOrderAccepted and ServiceOrderAccepted

Thanks

Pavel

**Comment by adrai** [comment]
I don’t know if it is common, but yes. It’s totally ok.

**Comment by bikerp** [comment]
@adrai Thanks
