### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by ssipos90** [adrai/node-cqrs-domain#157]
Hi,

can you update deps?

lodash and dotty have some issues (prototype pollution, moderate and severe) reported by npm audit.

**Comment by emmkong** [comment]
Is this lib still being maintained?

**Comment by goloroden** [comment]
Hey @ssipos90 @emmkong 👋

Currently, we do not actively work on this module, but this may change in the future.

If, for now, you are looking for an up-to-date alternative, I'd recommend that you take a look at [wolkenkit](https://wolkenkit.io/)

**Comment by ssipos90** [comment]
> Is this lib still being maintained?

I don't know. I don't see a deprecation notice. I know @adrai gave it to you guys.

If this is dead, I'll fork it for myself and keep working on it.

**Comment by emmkong** [comment]
@goloroden, Our system is in production, it's not easy for us to switch.  If you guys aren't willing to looking after this lib, maybe someone else in the community likes to take over. 

@ssipos90 please let me know if you decided to fork.

**Comment by goloroden** [comment]
@ssipos90 Although we aren't saying that we won't continue working on this in the future, at least right now we don't have specific plans for this, so feel free to fork.
