### ISSUE TITLE
Feature req: More flexible mapping: command <-> pre-condition

### ISSUE THREAD

**Issue by andywer** [adrai/node-cqrs-domain#28]
Instead of just being able to map command and pre-condition 1:1 or a pre-condition to all commands of an aggregate, I'd need to be able to map commands and pre-conditions more flexibly.

Current situation:
I've got two commands depending on the same pre-condition. Both belonging to the same aggregate, but these are not the only commands of the aggregate.

Suggestion:
```js
module.exports = require('cqrs-domain').defineCommand({
  preConditions: ['myPreCondition']
}, function(data, aggregate) {
  ...
});
```

**Comment by andywer** [comment]
Never mind. Just realized that I need a different pre-condition for the second command...
But maybe it's useful for other scenarios.

**Comment by adrai** [comment]
Better the other way round... define the commands in the pre-condition... Let's see it for the next case...
