### ISSUE TITLE
How to cause CommandRejected event to be generated?

### ISSUE THREAD

**Issue by nizachon** [adrai/node-cqrs-domain#29]
*domain.createCommandRejectedEvent()* will not create a *CommandRejected* event unless it's *error* parameter is one of 5 pre-defined Error types from lib/errors.

But how can my code import any of those types? So far, I have been unable to come up with anything better than:

```javascript
var ValidationError = require('../../../../../../node_modules/cqrs-domain/lib/errors/validationError.js');
```

Of course, I am new to node.js, so... :-)

**Comment by adrai** [comment]
The type (prototype) of the events are note exposed. Why do you need it? Can't you simple check err.name
or
subscribe to domain.onEvent(function (evt) {}); ?

**Comment by nizachon** [comment]
Type of the events or type of the errors? It's the latter (the error types) I was talking about.

In my case, I had to implement custom command handler to perform cross-aggregate validation (check that the aggregate referenced by *parentId* property of the command already exists.) If that validation failed, I would call the callback with *ValidationError* and that would eventually cause *domain.createCommandRejectedEvent()* to create a *CommandRejected* event. The problem is that neither *ValidationError* nor any other pre-defined error type that *createCommandRejectedEvent* method checks against are exposed (?). Any other error type causes *createCommandRejectedEvent* to do nothing.

https://github.com/adrai/node-cqrs-domain/blob/master/lib/domain.js#L173

The code:
```javascript
module.exports = require('cqrs-domain').defineCommandHandler({
}, function (aggregateId, command, commandHandler, callback) {
    // if 'command.parentEntryId' is provided, check that the parent entity exists
    // everything else - just follow DefaultCommandHandler

    var self = this;

    var parentId = !!this.definitions.command.payload && !!command.payload.parentEntityId
        ? command.payload.parentEntityId
        : null;  // use 'dotty'

    async.waterfall([
            function (clb) {
                if (!!parentId) {
                    self.loadAggregate(command.payload.parentEntityId, clb);
                } else {
                    clb(null, null, null, false);
                }
            },
            function (aggregate, stream, isNewSnapShotNeeded, clb) {
                if (!!parentId && (!aggregate || aggregate.getRevision() === 0)) {
                    clb(// new ValidationError('Parent Entity with id: ' + parentId + ' does not exist')

                         { name: 'ValidationError', message: 'Parent Entity with id: ' + parentId + ' does not exist' }
                    );
                } else {
                    clb(null);
                }
            }
        ],
        function (err) {
            if (!!err) {
                callback(err);
            } else {
                self.workflow(aggregateId, command, callback);
            }
        }
    )
});

```

**Comment by adrai** [comment]
Ok I see what you mean... I will expose these errors for the next release, ok?

**Comment by nizachon** [comment]
Thank you!

**Comment by adrai** [comment]
v1.4.1
