### ISSUE TITLE
Using 'instanceof' to check for the given type

### ISSUE THREAD

**Issue by nizachon** [adrai/node-cqrs-domain#30]
Adriano,

Please refer to: https://github.com/adrai/node-eventstore/issues/28

**cqrs-domain** has the similar issue, where type check using *instanceof* would fail if the object instance has been instantiated by a version of **cqrs-domain** other than the one that actually performs the check.

See, for example, https://github.com/adrai/node-cqrs-domain/blob/master/lib/structure/structureLoader.js#L21 and below:

```javascript
function isContext (item) {
  if (item.fileType !== 'js') {
    return false;
  }

  return item.value instanceof Context;
}

...
```

In my case, I have a module **A** that requires another module **B**, which in turn requires **cqrs-domain**. 

* A
 * cqrs-domain (1)
 * B
   * cqrs-domain (2)

For testing purposes **A** defines the domain tree and so also needs to require **cqrs-domain**. Sure enough, the *structureLoader* fails to load anything but *.json files.

Would this fix the problem?

```javascript
...
return item.value.constructor.name === 'Context'
```

Note: the problem is not limited to *structureLoader*, of course.

-Leo

**Comment by adrai** [comment]
Hmmm, what if B has an other version of cqrs-domain? You really want to load that files that probably has an other feature set?

An other solution could be to expose cqrs-domain in B, so A can use it.

What do you think?

**Comment by nizachon** [comment]
Having **B** expose **cqrs-domain** sounds interesting, I will give it a try.

Having said that, I still believe that usage of *instanceof* in JS should be limited to those cases when there is 100% guarantee that the instance and the checking code came from the source (*your* own code.)

What if someone alters the *Context* object by deleting the "feature" the framework expects? Or replaces it with a different implementation? It's a dynamically typed language, after all. How would *instanceof* protect you from those modifications?

**Comment by nizachon** [comment]
> Having B expose cqrs-domain sounds interesting, I will give it a try.

Works great. Thanks!

**Comment by TomKaltz** [comment]
@nizachon do you think you can provide a pseudo-code example of using node-cqrs-domain in a hierarchical structure like this?  I am very interested.
