### ISSUE TITLE
Cassandra for event storage

### ISSUE THREAD

**Issue by TomKaltz** [adrai/node-cqrs-domain#32]
Any thoughts on using distributed data storage engine for the event store?

**Comment by adrai** [comment]
Why not? Feel free to do a pull request...

**Comment by TomKaltz** [comment]
I'm interested in your thoughts regarding revision guard with distributed
systems.

**Comment by adrai** [comment]
Which revisionGuard? Not in the domain, but in the denormalizer?

**Comment by TomKaltz** [comment]
Ah yes I am a bit lost here.  I am still getting to know the world of CQRS.

**Comment by adrai** [comment]
The revisionGuard has 2 tasks to solve: dedublicate events and reorder incomming events. If you can guarantee this in your messaging system you don't need a revisionGuard.
Assuming you need the revisionGuard: When scaling the denormalizer process and you do not guarantee that the events of an aggregate goes to the same process (some sort of stickiness) you must check for some concurrency cases...

We do use revisionGuards in our distributed systems and we don't see any problem right now...

...what is the intent of you question? Did I catch what you asked for? Sorry I'm a little bit tired today...

**Comment by TomKaltz** [comment]
Adriano, thanks a lot.  My question regarded the general concerns of
concurrency in CQRS and distributed systems and was off-topic.  Thanks for
clarifying what did.  Your knowledge is greatly appreciated.
