### ISSUE TITLE
Feature request: Breaking hard dependency on 'node-eventstore'

### ISSUE THREAD

**Issue by nizachon** [adrai/node-cqrs-domain#33]
Adriano,

We have been using *node-cqrs-domain* intensively for quite awhile in development here, and like it a lot, but there is **one** thing that really throws us off: that the generic domain framework is coupled with the very specific implementation of Event Store (Node clone of NEventStore, to be precise.)

In our case we are using Greg Young's Event Store ("GetEventStore"), and to use it with node-cqrs-domain we have no other choice but to implement the custom "store" (in *node-eventstore* terms), which acts as an adapter to/from our Node http interface to GetEventStore.

For us, *node-eventstore* does not add any value, but rather creates extra overhead, which the adapter has to deal with (like event conversion, etc.)

In our opinion, in a **perfect world**, the domain framework would not know what "Event Store" means. It would be given "something" that knows how, for the given aggregate type and id, to load that aggregate from its history; and another "something" that would know how to deal with snapshots.

But because we don't live in a perfect world, would replacing **specific type** dependency with **interface** dependency be something you might consider taking on?

The *Domain* constructor takes *options* argument, which has *eventStore* property describing configuration parameters for &lt;node-eventstore&gt;\eventStore. How about checking if *options.eventStore* property is a **function**, and if it is, then treat it as a factory method for creating an event store?

I believe that this is the public interface the custom event store would need to implement to make *node-cqrs-domain* happy:

```javascript
getFromSnapshot(query, function(err, snapshot, stream));
createSnapshot(query, function (err));
getNewId(function (err, id));
on(evtName, function ());
init(callback);
setEventToDispatched(evt, function (err));
```

Yes, *node-cqrs-domain* would still be dependent on *node-eventstore* module (because of *EventStream*), but we would be able to live with that :-)

What do you think?

**Comment by adrai** [comment]
Sounds interesting...
At the moment I think you have done the only possible thing (custom store).
If you really want such an interface to come fast I need your help (pull request), because I don't get enough time to do it...
But the idea is good :-)

**Comment by nizachon** [comment]
Will be more than happy to contribute.

And after thinking about it for just one more minute :-), it becomes clear that dependency on *node-eventstore* (through its EventStream) can be eliminated completely by having the custom event store using its own implementation of EventStream **interface** (that interface is all that the *node-cqrs-domain* cares about, right?)

Best,
-Leo

**Comment by adrai** [comment]
Nice... Yes I think so...



Il giorno 5-mar-2015, alle ore 16:16, nizachon <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Will be more than happy to contribute.

And after thinking about it for just one more minute :-), it becomes clear that dependency on node-eventstore (through its EventStream) can be eliminated completely by having the custom event store using its own implementation of EventStream interface (that interface is all that the node-cqrs-domain cares about, right?)

Best,
-Leo

-

**Comment by nizachon** [comment]
From my original post: "How about checking if *options.eventStore* property is a function, and if it is, then treat it as a factory method for creating an event store?"

How would you feel about introducing a **breaking change**? If we just **allow** *options.eventStore* to be a factory method, but if it's not, than still taking the old path of treating it as an options argument for the hardcoded *node-eventstore*, then we won't achieve our goal of making *node-cqrs-domain* independent from *node-eventstore*, correct? 

So what if we **require** *options.eventStore* to be a factory method (a closure), and if it is not, just throw?

Then if somebody wanted to use *node-eventstore* with MongoDB, they would have in **their** code:

```javascript

// the client code depends on node-eventstore, but not the framework!
var eventstore = require('eventstore');

var domain = require('cqrs-domain')({
  domainPath: '/path/to/my/files',
  commandRejectedEventName: 'rejectedCommand',
  retryOnConcurrencyTimeout: 1000,
  snapshotThreshold: 1000,
  eventStore: function () {
     return eventstore({
        type: 'mongodb',
        host: 'localhost', 
        port: 27017,
        dbName: 'domain',
        eventsCollectionName: 'events',
        snapshotsCollectionName: 'snapshots', 
        transactionsCollectionName: 'transactions',
        timeout: 10000
        // username: 'technicalDbUser', 
        // password: 'secret'
    });
  },
.......
```

And for the custom event store it would look like this:

```javascript

var eventstore = require('./myeventstore.js');

var domain = require('cqrs-domain')({
  domainPath: '/path/to/my/files',
  commandRejectedEventName: 'rejectedCommand',
  retryOnConcurrencyTimeout: 1000,
  snapshotThreshold: 1000,
  eventStore: function () {
     return myeventstore({
        ........................
    });
  },
.......
```

Please let me know what you think. If breaking backwards compatibility makes you uneasy, then I will just add a factory option and will leave the default path (and module dependency on *node-eventstore*) intact.

**Comment by adrai** [comment]
Hmmmmm good question....
@jamuhl what's your opinion?

**Comment by jamuhl** [comment]
@adrai nothing against breaking change...as long it's documented and right semver ;)

**Comment by jamuhl** [comment]
@adrai or do some deprecation over 2 versions.

**Comment by adrai** [comment]
If only factory, I would handle the aggregateLock the same way (and expose it)

**Comment by adrai** [comment]
@nizachon go for it, by reflecting the above comments... ;-)

**Comment by nizachon** [comment]
Thank you, guys!

**Comment by adrai** [comment]
One more advice...
For a first step I would not remove the eventstore dep because the initialization of cqrs-domain is like cqrs-eventdenormalizer and cqrs-saga

**Comment by nizachon** [comment]
Got it

**Comment by adrai** [comment]
v1.4.10
