### ISSUE TITLE
Integration Test fails at: integrationTest.js line 77 

### ISSUE THREAD

**Issue by nizachon** [adrai/node-cqrs-domain#34]
Is domain structure, as returned by *domain.getInfo()*, sorted? What I get comes in order different from what the test expects:

![image](https://cloud.githubusercontent.com/assets/5288680/6513036/4ce68a5e-c335-11e4-91b6-5e2e00b25a15.png)

**Comment by adrai** [comment]
No it's not... I never tested on Windows...
I see no problem if you want to sort it...

**Comment by nizachon** [comment]
I don't think the result needs to be sorted just to satisfy the test. It's the test that should stop assuming that the result will have its data in some predictable order.

**Comment by adrai** [comment]
Yes, so sort it in the test ;-)
