### ISSUE TITLE
custom command validation?

### ISSUE THREAD

**Issue by stephanos** [adrai/node-cqrs-domain#38]
How can I use https://github.com/hapijs/joi to do the command validation instead of tv4? Something like a custom validation function on the command definition maybe?

**Comment by adrai** [comment]
Yes, there should be something...
call `defineValidation` and pass in a function that expects the cmd to be passed in...

**Comment by adrai** [comment]
And return a ValidationError

**Comment by stephanos** [comment]
Thanks for the quick response! I just read the documentation and didn't see it there.

Works like a charm :)

**Comment by adrai** [comment]
Undocumented feature ;-)
