### ISSUE TITLE
how to deal with side effects?

### ISSUE THREAD

**Issue by stephanos** [adrai/node-cqrs-domain#39]
Is there a best practice on how to deal with side effects (e.g. email sending, external API calls)? If implemented in events, a replay of events would re-trigger them, which is usually not what you want.

**Comment by adrai** [comment]
It really depends on your architecture but: you can use eventExtenders (will not be called during replay) or with viewBuilders by marking the used collection with "noReplay"

**Comment by stephanos** [comment]
Thanks for the suggestions! May I ask, how do you do it in your project(s)?

**Comment by adrai** [comment]
Stuff like email sending, with viewBuilders and eventExtenders...
And more important stuff with sagas... (cqrs-saga)

**Comment by stephanos** [comment]
Thanks.
