### ISSUE TITLE
store commands?

### ISSUE THREAD

**Issue by stephanos** [adrai/node-cqrs-domain#42]
I think there is a lot of value in storing each incoming command as well, not just the resulting events. Do you agree? Would that be outside the scope of the library?

**Comment by adrai** [comment]
this library uses event sourcing... so only storing events (these are the facts)
but if you need to store the commands just do it before handling them in cqrs-domain...
May I ask why you need to store them?

**Comment by stephanos** [comment]
I think (being a CQRS/ES-newbie) it can be useful for:
  - tracking the original trigger for one or multiple events, including meta data about the request (e.g. user agent) - leading to better debugging/auditing capabilities in production
  - being able to match an AJAX request with exactly one entity, the command - then one could easily reference the status of the command (e.g. if it was rejected: one could easily query for it and learn about that it was not valid, since there aren't any events in that case)
  - 'time travelling' (maybe?): in development, the client could display a number of successful commands and - on click - revert them
  - retry mechanism: *In addition, you can persist the Command messages to a store and easily support Re-playable Operations to handle retry logic or system restores* (from [CQRS Journey](https://msdn.microsoft.com/en-us/library/jj591627.aspx))

Maybe I'm wrong and all this can be achieved through events already. I'm very interested in what your experience taught you here :)

**Comment by adrai** [comment]
I recommend to do this outside of cqrs-domain...
Just one more advice: think about scalability&concurrency ;-)

**Comment by stephanos** [comment]
Thanks, just wanted to see your opinion :)
