### ISSUE TITLE
node-cqrs with Meteor, can 'domainPath' be optional?

### ISSUE THREAD

**Issue by eoliphan** [adrai/node-cqrs-domain#48]
Hi, I'm trying to use cqrs-domain in a meteor app as it's one of the more mature JS/CQRS implementations.  Given Meteor's build process, where it basically bundles up all the .js files, etc effectively renders whatever you set as a 'domainPath' invalid.  given that we can call say 'require('cqrs-domain').defineAggregate()' directly now.  Is the domainPath even used in this case.  I used this library on a node project some time ago, and I know it would do some 'magic' with the aggregate definitions, etc in the domain path.  BUt it looks like they can be defined explicitly in code now.

**Comment by adrai** [comment]
Do you mind doing a PR?

**Comment by eoliphan** [comment]
SUre, but I've not really tried to make it work, will make a pass and try

**Comment by eoliphan** [comment]
Hi I've figured this out, no changes needed. You just have to use the absolute directory.  Just grab process.env.PWD and tack on the other necessary directories
