### ISSUE TITLE
Delayed business rules validation

### ISSUE THREAD

**Issue by sbiaudet** [adrai/node-cqrs-domain#54]
I'd like to have a delayed business rules validation. In fact, if business rules failed i'd like to have only a notification/event without rejected error.

Your feeling ?

**Comment by adrai** [comment]
to have a normal event you have to handle it in the cmd handle section: https://github.com/adrai/node-cqrs-domain#command

**Comment by sbiaudet** [comment]
Yes I know the normal way ;)

If you have business rules defined and a business rules fail on a command, the command is rejected without applying events and it's normal. But in my process I want applying business rules in async and only check if aggregate is valid or not. Even if it is not valid I want applying events.

Perhaps we could have an implementation  like that :
```

module.exports = require('cqrs-domain').defineBusinessRule({
  // optional, default is file name without extension
  name: 'nameEquality',

  // optional
  description: 'firstname should never be equal lastname',

  // optional, default is false
  async: true,

  // optional, default Infinity, all business rules will be sorted by this value
  priority: 1
}, function (){ });


module.exports = require('cqrs-domain').defineCommand({
  // optional, default is file name without extension
  name: 'enterNewPerson',

  // optional, default 0
  version: 1,

  // optional, default false
  asyncBusinessRules: true,

  // optional, if not defined it will use what is defined as default in aggregate or pass the whole command
  payload: 'payload'
}, function (data, aggregate) { });

domain.onBusinessRulesError(function (aggregate, callback) {
  bus.emit('businnessRulesError', aggregate.BusinesRulesError[0], function ack () {
    callback();
  });
});
```

**Comment by adrai** [comment]
right now the business rules can be async (no problem) but on error applying the events smells wrong... :-(

**Comment by sbiaudet** [comment]
I understand, but it's like CQRS paradigm. You accept a delay between command and view-builders because in distributed environnement, data presented to the user is potentially obsolete. 

With complex business rule sometimes you could apply it in background and notify after your user that something is wrong. You UI can be faster and more fluid. User can enter lot of data in one time ("power typed") and after he solve errors in invalidated aggregate.

**Comment by adrai** [comment]
Why not using sagas instead?
