### ISSUE TITLE
Command Handler (Be careful!!!)

### ISSUE THREAD

**Issue by vishant-dhandha** [adrai/node-cqrs-domain#63]
**"Is your use case not solvable without a custom command handling? Sagas? Micro-Services?"**

can you please explain this question ?
does it mean that we don't need commandHandler for all commands?

i am using cqrs-sample in my project & my folder structure is below:
https://github.com/adrai/node-cqrs-domain/tree/master/test/integration/fixture/set2/person

Do i need to make commandHandler.js for handling commands?

**Comment by adrai** [comment]
no, command will be automatically handled by a default command handler....
a custom command handler is really just needed if you do hackie things...

**Comment by vishant-dhandha** [comment]
Thank you for you assistance...
