### ISSUE TITLE
How to append extra info (like session info ,data from async request) to the event?

### ISSUE THREAD

**Issue by vishant-dhandha** [adrai/node-cqrs-domain#67]
I want to append some info in event like session info, authToken , project key,etc.. to my data.

For this, i made a file in which there are async call to query the database.. the result should be appended to data .. and then aggregate.apply() method should be called..

I want to do this before event is created , so i think  [aggregate.apply()](https://github.com/adrai/node-cqrs-domain/blob/master/test/integration/fixture/set2/person/person.js#L29-L34) method is right place.. __what you think?Is this the right place to append data to the event?__

Secondly,I was thinking about using meta, but don't know how could i use this?

In ``` domain.defineCommand()``` you have mention about meta that
```javascript
// optional, if defined theses values will be copied to the event (can be used to transport information like userId, etc..)
  meta: 'meta' 
```

__By this do you mean that the values of meta should be come from command?__

**Comment by adrai** [comment]
yes, you can pass extra infos via command.meta to the event

**Comment by vishant-dhandha** [comment]
Is there any other way to achieve this?? 
i mean inside ``` domain.defineCommand() ``` i want to use my custom method to append data to event.. here is my code structure..
```javascript
module.exports = require('cqrs-domain').defineCommand({
    name: 'createNarration', 
    payload: 'payload'
}, function (data, aggregate) {
       require('/path/to/myfile.js').append(data, "createNarration", function(err, res){
        if(err){
           cosnole.log(err);
        }else{
           // Not working :Type Error is generated..
            aggregate.apply('narrationCreated', data);
        }
    });
})
```
If my code structure is like below, its working fine..
```javascript
module.exports = require('cqrs-domain').defineCommand({
    name: 'createNarration', 
    payload: 'payload'
}, function (data, aggregate) {
    //Working fine but i want to append info to data..
    aggregate.apply('narrationCreated', data);   
})
```

But i am using my custom method to fill data before event created. Though ```data``` is filled with my custom info but,
 The problem here i am facing is after appending data to events ,```aggregate.apply``` can not apply data to event ..
 Error is like 
```
 aggregate.apply('narrationCreated', data);
                      ^
TypeError: Object #<Object> has no method 'apply'
    at /home/vishant/Documents/cqrs-sample-vishant/domain/domainFiles/masters/narration/commands/createNarration.js:12:23
    at module.exports.append (/home/vishant/BizOs/bizosprojects/commonfeatures/eventdenormalizerservice/utility/commandappenderutil.js:155:13)
    at _asyncMap (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:254:17)
    at async.eachSeries.iterate (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:157:25)
    at _asyncMap (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:251:21)
    at async.series.results (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:615:34)
    at module.exports.append.async.series.data.error (/home/vishant/BizOs/bizosprojects/commonfeatures/eventdenormalizerservice/utility/commandappenderutil.js:150:17)
    at async.series.results (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:610:21)
    at _asyncMap (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:249:17)
    at async.eachSeries.iterate (/home/vishant/BizOs/bizosprojects/commonfeatures/node_modules/async/lib/async.js:149:13)

Process finished with exit code 8
```

___F.Y.I.  aggregate object has all the attribute & methods except 1 that is ```apply``` method___

**Comment by vishant-dhandha** [comment]
This is what i was trying to say.. I have replicate the issue ..
I have added a custom function to your cqrs-sample project.. Below is my commit to your repo..

https://github.com/vishant-dhandha/cqrs-sample/commit/20a0f2472366f44518f5dd122e20f20f9b6e9835

Here i have added async http call to fetch some info & append to the 'data'..

 At ```aggregate.apply('itemCreated', data);``` data contains my desired info but some how server stopped with TypeError: Object #Object has no method 'apply'

**Comment by adrai** [comment]
this is not possible... the whole apply part is completely sync...
can't you extend your command before it enters the domain.handle?

**Comment by vishant-dhandha** [comment]
I want to make a async call, if that async call successfully returned then and then only the event should be generated.
How could i make out this?

Saga is the solution for that???

**Comment by adrai** [comment]
```javascript
asynccall(function (err, extenstion) {

  if (!err) {
    command.myExtension = extension;
    domain.handle(command);
  }

});
```

**Comment by adrai** [comment]
I have an idea:
Would it be ok for you, if you define a precondition for that command in which you make your async requests and save the resulting data in a sort of clipboard on the aggregate and afterwards in de command just get that saved data and extend your event?

**Comment by vishant-dhandha** [comment]
Yes , this (precondition) solved my problem..
thank you
