### ISSUE TITLE
Unique entity business rule

### ISSUE THREAD

**Issue by gstrit** [adrai/node-cqrs-domain#70]
Hi,
I don't understand how to create a business rule which says : email adress is unique for all persons. I'm not able to access to the persons repository.
Thanks

**Comment by adrai** [comment]
business rules only applies on 1 aggregate (so you may need a personS aggregate)

**Comment by gstrit** [comment]
I have to have a person and a persons aggregate ? I'm not sure to understand how it should work

**Comment by adrai** [comment]
no, just a persons aggregate

**Comment by gstrit** [comment]
OK but can I apply a command createOnePerson to the persons aggregate ?
Thank you for your answers

**Comment by adrai** [comment]
Yes, an aggregate is not an object. it's a container for intensions.

**Comment by gstrit** [comment]
Ok I understand now how it should work but it doesn't work...

```
module.exports = require('cqrs-domain').definePreCondition({
    name: 'createPlayer',
    version: 0,
    description: 'unique email address'
}, function (data, agg) {
    var found = _.find(agg.get('players'), function (player) {
      return player.firstname === data.firstname;
    });
    if (found) {
      throw new Error('email already used');
    }
});
```

agg.get('players') is always empty.

**Comment by adrai** [comment]
how does your defineEvent file for playerCreated looks like?

**Comment by gstrit** [comment]
```
module.exports = require('cqrs-domain').defineEvent({
  name: 'playerCreated'
},
function (data, aggregate) {
    aggregate.get('players').push(data);
});
```

**Comment by adrai** [comment]
is that function called?

**Comment by gstrit** [comment]
yes it is

**Comment by adrai** [comment]
do you have this project hosted on github? can i look at it?

**Comment by gstrit** [comment]
https://github.com/gstrit/Test

**Comment by adrai** [comment]
You have to send all createPlayer commands with the same aggregateId

**Comment by gstrit** [comment]
In my domain, a player is an aggregate root not the collection. If I understand how it works, when a client send a command to update a player, he has to fill the id of the collection as the aggregateId and not the id of the player, right ?

**Comment by adrai** [comment]
no...
to play a bit, just extend your commands with (cmd.payload.id = 'same aggregate Id for all commands';)

the id of your collection player should be passed in the payload like (cmd.payload.playerId = 'vm.id')

**Comment by gstrit** [comment]
Ok thanks

**Comment by imissyouso** [comment]
sorry, I have the same question: how to make checks for uniqueness in domain? 
I tried to check it using eventDenormalizer by saving unique values (emails) into VM by listen domain events and then check it preCondition:
```
import * as domain from "cqrs-domain";

export = domain.definePreCondition({
    // @ts-ignore
    name: ['createUser', 'updateUser'],
    priority: 1,
    payload: 'payload',
},  (data, aggregate, callback) => {
    const usersRepo = require('../viewBuilders/user/usersCollection');
    usersRepo.findViewModels({email: data.email}, (err, items) => {
        if(items.length){
            callback("Provided email is already exist in our database!");
        } else {
            callback(null);
        }
    });
});
```
but this way is not atomic, theoretically there can be situation when 2 users can create their accounts with the same emails. How to avoid this?
