### ISSUE TITLE
Validation rule doesn't work

### ISSUE THREAD

**Issue by gstrit** [adrai/node-cqrs-domain#71]
Hi,

I'm trying to use the validation rule to validate the commands but it seems that the json files (schemas) are not used. Maybe I forgot something...

Thanks

**Comment by adrai** [comment]
compare with: https://github.com/adrai/node-cqrs-domain/tree/master/test/integration/fixture/set1 or: https://github.com/adrai/cqrs-sample/tree/master/domain/lib/item

**Comment by gstrit** [comment]
In fact I am already trying to work your example. The structureloader.js loads the JSON files correctly but it seems that the validator is undefined when the validate method is called in command.js.

**Comment by adrai** [comment]
You're right! I made a fix... can you retry?

**Comment by gstrit** [comment]
It's perfect now ! Thanks :)
