### ISSUE TITLE
Communicating between bounded contexts

### ISSUE THREAD

**Issue by hilkeheremans** [adrai/node-cqrs-domain#73]
Hey @adrai,

I would love your input on this. It regularly happens that we need to communicate between several bounded contexts at times. Ie, a change occurs in BC1 and we want BC2 to react or update some data in response to that. Let's assume it is OK if this update is eventually consistent (we are in a microservice situation). Creating one large bounded context or aggregate is not really an option in this case.

Since node-cqrs-domain does not seem to have a direct way of listening for / reacting to events originating from outside the domain, how would you organise this using your packages?

Some potential solutions I can imagine:
- using saga's to convert such events to commands: seems a little hackey since saga's are more intended for long lived processes
- using a hacked together custom command handler. Inevitably dirty.
- writing a custom converter which we hook up to node-cqrs-domain and which converts the events to commands

I'm probably missing a few ideas, which is why I'm reaching out. What would you recommend?

Thanks again for the great work!
Hilke

**Comment by pawarvijay** [comment]
some correction node-cqrs-domain [eats command and emits event](https://github.com/adrai/node-cqrs-domain#handling-a-command)

**Comment by hilkeheremans** [comment]
@pawarvijay Yes, I know, and that is exactly my point. Commands communicate intent and are usually triggered by an outside party, or sent by a saga.

There are times when you want one domain to update based on events that are emitted from another domain, even when this is done eventually (rather than immediate/transactionally). Ie, in this case, I would like the domain to listen not only for commands, but also for events that are emitted from other domain, and use those events to update its own state accordingly.

**Comment by adrai** [comment]
if stale data is ok... I would recommend a saga...
if not then custom command handler and pray ;-)

**Comment by hilkeheremans** [comment]
I'd prefer to avoid the praying part. But at least it seems I understood your packages well enough ;-)

Thanks!
