### ISSUE TITLE
Recommended strategy for disconnects

### ISSUE THREAD

**Issue by hilkeheremans** [adrai/node-cqrs-domain#78]
`node-cqrs-domain` has various events that designate disconnections in the event store, command bumper and aggregate lock.

In practice, we are using mongo as an event store. In this case, we need to handle all disconnections, since ignoring them can cause the `node-cqrs-domain` to hang; the backing mongo driver will not call back at all when the connection fails.

What would be your recommended strategy to handle this situation? Do you crash the entire process when a disconnect hits, or do you attempt to reconnect somehow?

**Comment by adrai** [comment]
We have larger complex setup deployed on a PaaS... there we do a process.exit(1)

**Comment by adrai** [comment]
...and additionally we use only 1 connection configured in the pool

i.e.
  settings.repository = {
    type: 'mongodb',
    url: storage.uri || storage.database_uri,
    timeout: 30 * 1000,
    heartbeat: 60 * 1000,
    options: {
      poolSize: 1
    }
  };

**Comment by hilkeheremans** [comment]
OK, perfect, that is exactly what I was thinking as well. We're running all this inside a bunch of docker containers, so easy enough.

BTW: Since we've been integrating your work all over, we have a list of items that could use some more attention, documentation-wise; once time permits, expect a whole bunch of small PRs across various repo's :-)

Thank you!
