### ISSUE TITLE
[Question] How would you validate a command that updates

### ISSUE THREAD

**Issue by AlexandreRoba** [adrai/node-cqrs-domain#84]
Hello, In one of my use cases, I would like the command to be rejected if it is an update command and the aggregate to update does not exist... Theorically this should not happen but... I have an Identity provider that generates commands. It first create the profile the first time the user logs in and if the user used facebook or linked to authenticate it download the avatar and generate an update command for the avatar.... then every time the user logs in, if the avatar or the information coming from facebook or linkedin has changed, It generates an update command for the profile micro service to update the facebook and linked display name or avatar.

Today I do the validation with a Precondition such as:
```javascript
module.exports = require('cqrs-domain').definePreCondition({
    name: 'updateProfileUserName',
    description: 'Aggregate Must Exist',
    priority: 1
}, function (data, aggregate) {
    if (aggregate.attributes._revision===0) {
        return 'Aggregate does not exist';
    }
});
```

I was wondering if that would be the way you would handle this?

Thanks

**Comment by adrai** [comment]
theres a built-in feature for that case...

existing: true

https://github.com/adrai/node-cqrs-domain#command

but you need to define this for each command

**Comment by AlexandreRoba** [comment]
Alright. My mistake. I did not catch that part :)
