### ISSUE TITLE
[Question] How to get aggregate state

### ISSUE THREAD

**Issue by timbset** [adrai/node-cqrs-domain#87]
Hello. I read docs many times but did not find any info about how to get aggregate state. I need to have possibility to reproduce state dynamically (after request) and cache it (reproduce on server start). Could you please show me how to implement it?

**Comment by adrai** [comment]
The aggregate "state" will be constructed each time a command is handled.

**Comment by adrai** [comment]
to have everything loaded on server start is not possible right now... and perhaps not such a good idea to have everything in the memory when your eventstore is big...

**Comment by timbset** [comment]
@adrai, thank you for the answer. And how can I reproduce the state on request with existing events?

**Comment by adrai** [comment]
What do you mean with "on request"? Can you describe the use case?

**Comment by timbset** [comment]
@adrai, the simplest case is users. I create user by command, modify aggregate by event. As I understand, by default on server start state is not reproduced with all users that were created earlier. And from client I need to request all users list so I need to get an array of users that were created after last server start and users saved in database earlier. The question is how to restore the state without side effects?

**Comment by adrai** [comment]
ohhh.... what you search is a read model...
checkout my (old) cqrs sample: https://github.com/adrai/cqrs-sample
you need more parts to fulfill the whole cqrs system: http://cqrs.js.org/
you need some denormalizers ;-)

**Comment by timbset** [comment]
@adrai, ok. Thank you for links. Hope it will help me
