### ISSUE TITLE
Using testing frameworks registered node module extentions

### ISSUE THREAD

**Issue by repkins** [adrai/node-cqrs-domain#89]
Hello!

I came to issue while I lauching test suites trough testing runners such as Mocha. My all code, including test suite code and domain definition files, have written in TypeScript, and I want to make run tests straighfully, i.e. TS compilation at runtime, using Mocha CLI `--compilers` argument. When i trying that way, it does not pass, like domain handler having no registered definitions, basing on exception thrown from domain manager, although domain definition code files is present. However, when i first transpile all code to plain javascript and launch test runner on that (of course without unneccesarry `--compilers` argument), then i see it pass without a problem.

I have digged in the code of domain and i find out cause of this. File structure "traverser" does not like file extentions other like `.js` and `.json`

**Comment by adrai** [comment]
exactly ;-)

**Comment by repkins** [comment]
So, can this to be resolved so it would not skip domain definition files with TS file extention `.ts` while running though registered runtime compiler?

**Comment by adrai** [comment]
If accepting ts files, I can't guarantee that the require statements will always work.
But feel free to submit a PR...

**Comment by repkins** [comment]
Maybe by passing file paths without file extensions, except `.json`,  to `require` statement? That lets node.js side decide which file load according by its registered loader extensions
