### ISSUE TITLE
CQRS full validation

### ISSUE THREAD

**Issue by timbset** [adrai/node-cqrs-domain#91]
Hello,

I have more philosophical question than is about your library. As I understand, when I handle command, I get aggregate on pre-condition. I want to create users with unique emails. How can I check that I have no users with that email?

**Comment by adrai** [comment]
If you really want to solve it in the domain, you need only 1 aggregate instance i.e. with a fix aggregate id (i.e. USER_EMAILS)

**Comment by timbset** [comment]
Thank you. And what do you mean saying 'if you really want'? Is it good to solve it somewhere outside the domain in middleware between request handling and commang execution? I just wanted to put all my logic to domain and write some simple express-to-cqrs adapter. Or is it a bad solution?

**Comment by adrai** [comment]
It's ok...
But I would decouple the whole Idm part (user stuff) from the domain...
I.e. By having an own authentication server

**Comment by timbset** [comment]
OK. Thank you for the answer. It was very useful
