### ISSUE TITLE
getInfo does not return the structure of defined commands

### ISSUE THREAD

**Issue by alemhnan** [adrai/node-cqrs-domain#94]
This is more a feature request than a bug.
I am wiring the commands into HTTP module using Swagger (with LoopBack). I would like to create one route for each command automatically and to specify as well the parameters needed. 

Using getInfo, I can get the command names, but I do not have access to the parameters needed (or at least it does not seem so). 

Is there a way to get that information at runtime? Otherwise, I will be happy to provide a PR (if you think that makes sense to have that). In such case could you point me the relevant codebase?

**Comment by adrai** [comment]
What do you mean by parameters? validation rules?

**Comment by alemhnan** [comment]
No sorry, my bad. I mean the input of the command. In your cqrs-sample, for `createItem` it will be `id`, `command`, and `payload.text`.

**Comment by adrai** [comment]
Do you mean this? https://github.com/adrai/cqrs-sample/blob/master/host/public/js/app.js#L202

**Comment by alemhnan** [comment]
As input yes. There you need to know a priori the structure of the command for every command in your system. What I would like is to have that structure (pretty much the json schemas defined in your command library I think) in the `getInfo()` method.

**Comment by adrai** [comment]
Probably I do not fully understand...
Can you do a little example on what you would expect?

**Comment by alemhnan** [comment]
Sure, I'll provide a small example tomorrow morning.

**Comment by alemhnan** [comment]
The `getInfo` of your example returns this:

```javascript
{ 
  name: 'createItem',
  version: 0,
  preConditions: [],
  preLoadConditions: []
}
```

Here I cannot inspect the payload structure. I would like something like this:

```javascript
{ 
  name: 'createItem',
  version: 0,
  preConditions: [],
  preLoadConditions: [],
  payload: {
    type: "object",
    properties: {
      text: { type: "string" }
    },
    required: ["text"]
  }
}
```

Now with that information, I can programmatically feed another representation (like Swagger for instance). The end goal is to generate a swagger interface like this:

![image](https://user-images.githubusercontent.com/1347688/27857976-d6fc57bc-6173-11e7-89b1-40336a224349.png)

Hence I need the name of the command and the payload to pass along (and hopefully nothing more but I'm still working on it).

Does it make sense?

**Comment by adrai** [comment]
So basically a part (the payload) of the validationRule...
The problem is, this is very specific...
In theory a command does not need to have a property 'payload', it can be anything... the structure of the message is not strict

**Comment by adrai** [comment]
But on your specific implementation you can extend it on your own...

**Comment by alemhnan** [comment]
Ok, thanks for the answer. I'll look into it. Where do you suggest to look to extend for this use case?

**Comment by adrai** [comment]
directly after receiving the result of the getInfo function
